# See https://docs.travis-ci.com/user/languages/php

# travis.yml based on https://github.com/reeze/msgpack-hhvm/blob/master/.travis.yml

sudo: required
dist: trusty
group: edge 

# We run docker instead of 'php' because Ubuntu Trusty is too old for hhvm 3.22.1
services:
  - docker

script:
  - ci/main.sh

branches:
  only:
    - master

notifications:
 email: false
